# Fly.io configuration for VidProd
app = "vidprod-app"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  ENVIRONMENT = "production"
  WORKERS = "4"
  MAX_UPLOAD_SIZE = "100MB"
  CHUNK_SIZE = "5MB"
  CONCURRENT_UPLOADS = "3"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"
    tls_skip_verify = false

    [services.http_checks.headers]
      User-Agent = "Fly-HealthCheck"

# Persistent storage for uploads
[mounts]
  source = "vidprod_data"
  destination = "/data"

# Scaling configuration
[[regions]]
  iad = "primary"
  ord = "backup"

# Process groups
[processes]
  app = "bash start.sh"

# Deploy configuration
[deploy]
  release_command = "python backend/migrate.py"
  strategy = "rolling"

# Metrics
[metrics]
  port = 9091
  path = "/metrics"